"""
This type stub file was generated by pyright.
"""

from lazi.conf import conf as _conf
from .finder import Finder, __finder__

__all__ = ("Finder", "lazi", "lazy")
conf = _conf
lazi = ...
lazy = ...
if _conf.CORE_AUTO:
    ...
