"""
This type stub file was generated by pyright.
"""

from types import ModuleType

__all__ = ("Module", )
Spec = ...
Loader = ...
MODULE_SPEC_ATTR_MAP = ...
GETATTR_PASS = ...
SETATTR_PASS = ...
class Module(ModuleType):
    __name__: str
    __loader__: Loader
    __package__: str
    __spec__: Spec
    def __init__(self, spec: Spec, module: ModuleType) -> None:
        ...
    
    def __getattribute__(self, attr) -> Any:
        ...
    
    def __setattr__(self, attr, valu) -> None:
        ...
    


