"""
This type stub file was generated by pyright.
"""

import importlib.util
import logging
import logging.handlers
import mimetypes
import os
import pathlib
import queue
import sys
import time
import traceback
import werkzeug
import werkzeug.local
import werkzeug.test
from datetime import datetime
from types import SimpleNamespace

__version__ = ...
werkzeug_local = ...
global_proxy = ...
log_formatter = ...
def get_app(app_map, log_level=..., log_handler=..., request_id_header=..., log_queue_length=..., abort_extra=...) -> Callable[..., Any]:
    ...

def configure_logging(log_level, log_queue_length, log_handler) -> tuple[Logger, EvictQueue, QueueListener]:
    ...

def process_module(module, response, params, logger, shallow_request=...):
    ...

def validate_response(response_in, response_out):
    ...

def get_module(path) -> ModuleType | None:
    ...

def get_http_error_handler(error_code) -> ModuleType | None:
    ...

def get_processors(http_method) -> tuple[ModuleType | None, type[DirectFileServe] | ModuleType | None, ModuleType | None]:
    ...

def find_processor_path(suffix_list) -> str | None:
    ...

def get_search_paths(site_path, url_path_str) -> list[Any]:
    ...

def run_func_with_dict(input_dict, func):
    ...

class DirectFileServe:
    @staticmethod
    def main(response):
        ...
    


class CustomQueueHandler(logging.handlers.QueueHandler):
    """Extend QueueHandler to attach Flask request context to record since
    request context won't be available inside listener thread.
    """
    def prepare(self, record) -> LogRecord:
        ...
    


class EvictQueue(queue.Queue):
    def put(self, item, block=..., timeout=...) -> None:
        ...
    


class RedirectCustomClass(werkzeug.exceptions.HTTPException):
    description = ...


class RedirectMovedPermanently(RedirectCustomClass):
    code = ...
    name = ...


class RedirectFound(RedirectCustomClass):
    code = ...
    name = ...


class RedirectSeeOther(RedirectCustomClass):
    code = ...
    name = ...


class RedirectTemporaryRedirect(RedirectCustomClass):
    code = ...
    name = ...


class RedirectPermanentRedirect(RedirectCustomClass):
    code = ...
    name = ...


