"""
This type stub file was generated by pyright.
"""

import torch
from typing import Dict, List, Optional, Union
from torch import nn
from dataclasses import dataclass
from .model import CLIPTextCfg, CLIPVisionCfg

GENERATION_TYPES = ...
_has_transformers = ...
@dataclass
class MultimodalCfg(CLIPTextCfg):
    mlp_ratio: int = ...
    dim_head: int = ...
    heads: int = ...
    n_queries: int = ...
    attn_pooler_heads: int = ...


class CoCa(nn.Module):
    def __init__(self, embed_dim, multimodal_cfg: MultimodalCfg, text_cfg: CLIPTextCfg, vision_cfg: CLIPVisionCfg, quick_gelu: bool = ..., init_logit_scale: float = ..., init_logit_bias: Optional[float] = ..., nonscalar_logit_scale: bool = ..., cast_dtype: Optional[torch.dtype] = ..., pad_id: int = ...) -> None:
        ...
    
    @torch.jit.ignore
    def set_grad_checkpointing(self, enable: bool = ...) -> None:
        ...
    
    def encode_image(self, images, normalize: bool = ...) -> Tensor | Any:
        ...
    
    def encode_text(self, text, normalize: bool = ...) -> Tensor | Any:
        ...
    
    def forward_intermediates(self, image: Optional[torch.Tensor] = ..., text: Optional[torch.Tensor] = ..., image_indices: Optional[Union[int, List[int]]] = ..., text_indices: Optional[Union[int, List[int]]] = ..., stop_early: bool = ..., normalize: bool = ..., normalize_intermediates: bool = ..., intermediates_only: bool = ..., image_output_fmt: str = ..., image_output_extra_tokens: bool = ..., text_output_fmt: str = ..., text_output_extra_tokens: bool = ..., output_logits: bool = ..., output_logit_scale_bias: bool = ...) -> Dict[str, Union[torch.Tensor, List[torch.Tensor]]]:
        """ Forward features that returns intermediates.

        Args:
            image: Input image tensor
            text: Input text tensor
            image_indices: For image tower, Take last n blocks if int, all if None, select matching indices if sequence
            text_indices: Take last n blocks if int, all if None, select matching indices if sequence
            stop_early: Stop iterating over blocks when last desired intermediate hit
            normalize: L2 Normalize final image and text features (if present)
            normalize_intermediates: Apply final encoder norm layer to all intermediates (if possible)
            intermediates_only: Only return intermediate features, do not return final features
            image_output_fmt: Shape of intermediate image feature outputs
            image_output_extra_tokens: Return both prefix and spatial intermediate tokens
            text_output_fmt: Shape of intermediate text feature outputs
            text_output_extra_tokens: Return both prefix and spatial intermediate tokens
            output_logits: Include logits in output
            output_logit_scale_bias: Include the logit scale bias in the output
        Returns:

        """
        ...
    
    def forward(self, image, text: Optional[torch.Tensor] = ..., image_latent: Optional[torch.Tensor] = ..., image_embs: Optional[torch.Tensor] = ..., output_labels: bool = ...) -> dict[str, Tensor | None] | dict[str, Tensor | Any | None]:
        ...
    
    def generate(self, image, text=..., seq_len=..., max_seq_len=..., temperature=..., generation_type=..., top_p=..., top_k=..., pad_token_id=..., eos_token_id=..., sot_token_id=..., num_beams=..., num_beam_groups=..., min_seq_len=..., stopping_criteria=..., repetition_penalty=..., fixed_output_length=...) -> Tensor:
        ...
    


def prepare_inputs_for_generation(input_ids, image_inputs, past=..., **kwargs) -> dict[str, Any | None]:
    ...

