"""
This type stub file was generated by pyright.
"""

import torch
from typing import Union
from .model import CLIP, CustomTextCLIP

""" Conversion functions for 3rd part state-dicts and non-torch native checkpoint formats.
"""
@torch.no_grad()
def load_big_vision_weights(model: CustomTextCLIP, checkpoint_path: str) -> None:
    """ Load weights from .npz checkpoints for official Google big_vision image-text models

    Currently, the SigLIP source models are supported and a CustomTextCLIP destination model
    w/ timm image encoder.
    """
    ...

@torch.no_grad()
def convert_mobile_clip_state_dict(model: CustomTextCLIP, state_dict, fastvit=...) -> dict[str | Any, Tensor | Any]:
    ...

def convert_state_dict(model: Union[CustomTextCLIP, CLIP], state_dict) -> dict[str | Any, Tensor | Any]:
    ...

