"""
This type stub file was generated by pyright.
"""

import torch
import torch.nn as nn
from torch import TensorType
from transformers import PretrainedConfig
from transformers.modeling_outputs import BaseModelOutput

""" huggingface model adapter

Wraps HuggingFace transformers (https://github.com/huggingface/transformers) models for use as a text tower in CLIP model.
"""
_POOLERS = ...
def register_pooler(cls):
    """Decorator registering pooler class"""
    ...

@register_pooler
class MeanPooler(nn.Module):
    """Mean pooling"""
    def forward(self, x: BaseModelOutput, attention_mask: TensorType):
        ...
    


@register_pooler
class MaxPooler(nn.Module):
    """Max pooling"""
    def forward(self, x: BaseModelOutput, attention_mask: TensorType):
        ...
    


@register_pooler
class ClsPooler(nn.Module):
    """CLS token pooling"""
    def __init__(self, use_pooler_output=...) -> None:
        ...
    
    def forward(self, x: BaseModelOutput, attention_mask: TensorType):
        ...
    


@register_pooler
class ClsLastHiddenStatePooler(nn.Module):
    """CLS token pooling
    NOTE: this is equivalent to ClsPooler above with use_pooler_output=False
    """
    def __init__(self) -> None:
        ...
    
    def forward(self, x: BaseModelOutput, attention_mask: TensorType):
        ...
    


class HFTextEncoder(nn.Module):
    """HuggingFace model adapter"""
    output_tokens: torch.jit.Final[bool]
    def __init__(self, model_name_or_path: str, output_dim: int, config: PretrainedConfig = ..., pooler_type: str = ..., proj_type: str = ..., pretrained: bool = ..., output_tokens: bool = ...) -> None:
        ...
    
    def forward(self, x: TensorType) -> tuple[Any, Any] | Any:
        ...
    
    def lock(self, unlocked_layers: int = ..., freeze_layer_norm: bool = ...) -> None:
        ...
    
    @torch.jit.ignore
    def set_grad_checkpointing(self, enable=...) -> None:
        ...
    
    def init_parameters(self) -> None:
        ...
    


