"""
This type stub file was generated by pyright.
"""

import torch
from typing import Dict, List, Optional, Union
from torch import nn

class Bottleneck(nn.Module):
    expansion = ...
    def __init__(self, inplanes, planes, stride=...) -> None:
        ...
    
    def forward(self, x: torch.Tensor) -> Any:
        ...
    


class AttentionPool2d(nn.Module):
    def __init__(self, spacial_dim: int, embed_dim: int, num_heads: int, output_dim: int = ...) -> None:
        ...
    
    def forward(self, x) -> Tensor:
        ...
    


class ModifiedResNet(nn.Module):
    """
    A ResNet class that is similar to torchvision's but contains the following changes:
    - There are now 3 "stem" convolutions as opposed to 1, with an average pool instead of a max pool.
    - Performs antialiasing strided convolutions, where an avgpool is prepended to convolutions with stride > 1
    - The final pooling layer is a QKV attention instead of an average pool
    """
    def __init__(self, layers: List[int], output_dim: int, heads: int, image_size: int = ..., width: int = ...) -> None:
        ...
    
    def init_parameters(self) -> None:
        ...
    
    def lock(self, unlocked_groups=..., freeze_bn_stats=...) -> None:
        ...
    
    @torch.jit.ignore
    def set_grad_checkpointing(self, enable=...) -> None:
        ...
    
    def stem(self, x) -> Any:
        ...
    
    def forward_intermediates(self, x: torch.Tensor, indices: Optional[Union[int, List[int]]] = ..., stop_early: bool = ..., normalize_intermediates: bool = ..., intermediates_only: bool = ..., output_fmt: str = ..., output_extra_tokens: bool = ...) -> Dict[str, Union[torch.Tensor, List[torch.Tensor]]]:
        """ Forward features that returns intermediates.

        Args:
            x: Input image tensor
            indices: Take last n blocks if int, all if None, select matching indices if sequence
            stop_early: Stop iterating over blocks when last desired intermediate hit
            normalize_intermediates: Apply final norm layer to all intermediates
            intermediates_only: Only return intermediate features
            output_fmt: Shape of intermediate feature outputs
            output_extra_tokens: Return both extra class, eot tokens
        Returns:

        """
        ...
    
    def forward(self, x) -> Any:
        ...
    


