"""
This type stub file was generated by pyright.
"""

import torch
from typing import List, Optional, Union

""" OpenAI pretrained model functions

Adapted from https://github.com/openai/CLIP. Originally MIT License, Copyright (c) 2021 OpenAI.
"""
__all__ = ["list_openai_models", "load_openai_model"]
def list_openai_models() -> List[str]:
    """Returns the names of available CLIP models"""
    ...

def load_openai_model(name: str, precision: Optional[str] = ..., device: Optional[Union[str, torch.device]] = ..., cache_dir: Optional[str] = ...) -> CLIP:
    """Load a CLIP model

    Parameters
    ----------
    name : str
        A model name listed by `clip.available_models()`, or the path to a model checkpoint containing the state_dict
    precision: str
        Model precision, if None defaults to 'fp32' if device == 'cpu' else 'fp16'.
    device : Union[str, torch.device]
        The device to put the loaded model
    cache_dir : Optional[str]
        The directory to cache the downloaded model weights

    Returns
    -------
    model : torch.nn.Module
        The CLIP model
    preprocess : Callable[[PIL.Image], torch.Tensor]
        A torchvision transform that converts a PIL image into a tensor that the returned model can take as its input
    """
    ...

