"""
This type stub file was generated by pyright.
"""

def get_2d_sincos_pos_embed(embed_dim, grid_size, cls_token=...) -> NDArray[float64] | NDArray[Any]:
    """
    grid_size: int of the grid height and width
    return:
    pos_embed: [grid_size*grid_size, embed_dim] or [1+grid_size*grid_size, embed_dim] (w/ or w/o cls_token)
    """
    ...

def get_2d_sincos_pos_embed_from_grid(embed_dim, grid) -> NDArray[Any]:
    ...

def get_1d_sincos_pos_embed_from_grid(embed_dim, pos) -> NDArray[Any]:
    """
    embed_dim: output dimension for each position
    pos: a list of positions to be encoded: size (M,)
    out: (M, D)
    """
    ...

def interpolate_pos_embed(model, checkpoint_model) -> None:
    ...

