"""
This type stub file was generated by pyright.
"""

import torch
import torch.nn as nn
from typing import Dict, List, Optional, Tuple, Union

""" timm model adapter

Wraps timm (https://github.com/rwightman/pytorch-image-models) models for use as a vision tower in CLIP model.
"""
class TimmModel(nn.Module):
    """ timm model adapter
    """
    def __init__(self, model_name: str, embed_dim: int, image_size: Union[int, Tuple[int, int]] = ..., pool: str = ..., proj: str = ..., proj_bias: bool = ..., drop: float = ..., drop_path: Optional[float] = ..., patch_drop: Optional[float] = ..., pretrained: bool = ...) -> None:
        ...
    
    def lock(self, unlocked_groups: int = ..., freeze_bn_stats: bool = ...) -> None:
        """ lock modules
        Args:
            unlocked_groups (int): leave last n layer groups unlocked (default: 0)
        """
        ...
    
    @torch.jit.ignore
    def set_grad_checkpointing(self, enable: bool = ...) -> None:
        ...
    
    def forward_intermediates(self, x: torch.Tensor, indices: Optional[Union[int, List[int]]] = ..., stop_early: bool = ..., normalize_intermediates: bool = ..., intermediates_only: bool = ..., output_fmt: str = ..., output_extra_tokens: bool = ...) -> Dict[str, Union[torch.Tensor, List[torch.Tensor]]]:
        """ Forward features that returns intermediates.

        Args:
            x: Input image tensor
            indices: Take last n blocks if int, all if None, select matching indices if sequence
            stop_early: Stop iterating over blocks when last desired intermediate hit
            normalize_intermediates: Apply norm layer to all intermediates
            intermediates_only: Only return intermediate features
            output_fmt: Shape of intermediate feature outputs
            output_extra_tokens: Return both prefix and spatial intermediate tokens
        Returns:
        """
        ...
    
    def set_input_size(self, image_size: Union[int, Tuple[int, int]]) -> None:
        """Set the input image size for the model after initialization.

        This method attempts to call set_input_size on the underlying timm model
        if it supports dynamic input size adjustment.

        Args:
            image_size: New image size as int (square) or tuple (h, w)
        """
        ...
    
    def forward(self, x) -> Any:
        ...
    


