"""
This type stub file was generated by pyright.
"""

import torch
from functools import lru_cache
from typing import Callable, List, Optional, Union

""" CLIP tokenizer

Copied from https://github.com/openai/CLIP. Originally MIT License, Copyright (c) 2021 OpenAI.
"""
_nltk_init = ...
DEFAULT_CONTEXT_LENGTH = ...
@lru_cache()
def default_bpe() -> str:
    ...

@lru_cache()
def bytes_to_unicode() -> dict[int, str]:
    """
    Returns list of utf-8 byte and a corresponding list of unicode strings.
    The reversible bpe codes work on unicode strings.
    This means you need a large # of unicode characters in your vocab if you want to avoid UNKs.
    When you're at something like a 10B token dataset you end up needing around 5K for decent coverage.
    This is a significant percentage of your normal, say, 32K bpe vocab.
    To avoid that, we want lookup tables between utf-8 bytes and unicode strings.
    And avoids mapping to whitespace/control characters the bpe code barfs on.
    """
    ...

def get_pairs(word) -> set[Any]:
    """Return set of symbol pairs in a word.
    Word is represented as tuple of symbols (symbols being variable-length strings).
    """
    ...

def basic_clean(text) -> str:
    ...

def whitespace_clean(text) -> str:
    ...

def get_clean_fn(type: str) -> Callable[..., str]:
    ...

def canonicalize_text(text, *, keep_punctuation_exact_string=..., trans_punctuation: dict = ...) -> str:
    """Returns canonicalized `text` (lowercase and punctuation removed).

    From: https://github.com/google-research/big_vision/blob/53f18caf27a9419231bbf08d3388b07671616d3d/big_vision/evaluators/proj/image_text/prompt_engineering.py#L94

    Args:
      text: string to be canonicalized.
      keep_punctuation_exact_string: If provided, then this exact string kept.
        For example providing '{}' will keep any occurrences of '{}' (but will
        still remove '{' and '}' that appear separately).
    """
    ...

class SimpleTokenizer:
    def __init__(self, bpe_path: str = ..., additional_special_tokens: Optional[List[str]] = ..., context_length: Optional[int] = ..., clean: str = ..., reduction_mask: str = ...) -> None:
        ...
    
    def bpe(self, token) -> str | LiteralString:
        ...
    
    def encode(self, text) -> list[Any]:
        ...
    
    def decode(self, tokens) -> str:
        ...
    
    def __call__(self, texts: Union[str, List[str]], context_length: Optional[int] = ...) -> torch.LongTensor:
        """ Returns the tokenized representation of given input string(s)

        Parameters
        ----------
        texts : Union[str, List[str]]
            An input string or a list of input strings to tokenize
        context_length : int
            The context length to use; all CLIP models use 77 as the context length

        Returns
        -------
        A two-dimensional tensor containing the resulting tokens, shape = [number of input strings, context_length]
        """
        ...
    


_tokenizer = ...
def decode(output_ids: torch.Tensor) -> str:
    ...

def tokenize(texts: Union[str, List[str]], context_length: int = ...) -> torch.LongTensor:
    ...

def random_mask_tokenize(texts: Union[str, List[str]], context_length: int, sot_token_id: int, eot_token_id: int, encode_fn: Callable, shuffle: bool = ...) -> Tensor:
    ...

def simple_mask_tokenize(texts: Union[str, List[str]], context_length: int, sot_token_id: int, eot_token_id: int, encode_fn: Callable) -> Tensor:
    ...

def syntax_mask_tokenize(texts: Union[str, List[str]], context_length: int, sot_token_id: int, eot_token_id: int, encode_fn: Callable) -> torch.LongTensor:
    """ Returns the tokenized representation of given input string(s).
    Apply syntax masking before tokenize.
    """
    ...

def get_reduction_mask_fn(type: str) -> Callable[..., Tensor] | partial[Tensor] | Callable[..., LongTensor]:
    """ Choose strategy for dropping (masking) tokens to achieve target context length"""
    ...

class HFTokenizer:
    """HuggingFace tokenizer wrapper with support for custom tokenization modes"""
    def __init__(self, tokenizer_name: str, context_length: Optional[int] = ..., clean: str = ..., strip_sep_token: bool = ..., language: Optional[str] = ..., cache_dir: Optional[str] = ..., tokenizer_mode: Optional[str] = ..., **kwargs) -> None:
        ...
    
    def save_pretrained(self, dest) -> None:
        ...
    
    def __call__(self, texts: Union[str, List[str]], context_length: Optional[int] = ...) -> torch.Tensor:
        ...
    
    def set_language(self, src_lang) -> None:
        ...
    


class SigLipTokenizer:
    """HuggingFace tokenizer wrapper for SigLIP T5 compatible sentencepiece vocabs

    NOTE: this is not needed in normal library use, but is used to import new sentencepiece tokenizers
    into OpenCLIP. Leaving code here in case future models use new tokenizers.
    """
    VOCAB_FILES = ...
    def __init__(self, tokenizer_name: str, context_length: Optional[int] = ...) -> None:
        ...
    
    def save_pretrained(self, dest) -> None:
        ...
    
    def __call__(self, texts: Union[str, List[str]], context_length: Optional[int] = ...) -> torch.Tensor:
        ...
    


