"""
This type stub file was generated by pyright.
"""

import torch
from dataclasses import dataclass
from typing import Any, Dict, List, Optional, Tuple, Union
from torchvision.transforms import ToTensor

@dataclass
class PreprocessCfg:
    size: Union[int, Tuple[int, int]] = ...
    mode: str = ...
    mean: Tuple[float, ...] = ...
    std: Tuple[float, ...] = ...
    interpolation: str = ...
    resize_mode: str = ...
    fill_color: int = ...
    def __post_init__(self) -> None:
        ...
    
    @property
    def num_channels(self) -> Literal[3]:
        ...
    
    @property
    def input_size(self) -> tuple[Literal[3], int, int] | tuple[Literal[3], *tuple[int, ...]]:
        ...
    


_PREPROCESS_KEYS = ...
def merge_preprocess_dict(base: Union[PreprocessCfg, Dict], overlay: Dict) -> dict[str, Any] | dict[Any, Any]:
    """ Merge overlay key-value pairs on top of base preprocess cfg or dict.
    Input dicts are filtered based on PreprocessCfg fields.
    """
    ...

def merge_preprocess_kwargs(base: PreprocessCfg, **kwargs) -> dict[str, Any] | dict[Any, Any]:
    ...

@dataclass
class AugmentationCfg:
    scale: Tuple[float, float] = ...
    ratio: Optional[Tuple[float, float]] = ...
    color_jitter: Optional[Union[float, Tuple[float, float, float], Tuple[float, float, float, float]]] = ...
    re_prob: Optional[float] = ...
    re_count: Optional[int] = ...
    use_timm: bool = ...
    color_jitter_prob: float = ...
    gray_scale_prob: float = ...


class ResizeKeepRatio:
    """ Resize and Keep Ratio

    Copy & paste from `timm`
    """
    def __init__(self, size, longest=..., interpolation=..., random_scale_prob=..., random_scale_range=..., random_aspect_prob=..., random_aspect_range=...) -> None:
        ...
    
    @staticmethod
    def get_params(img, target_size, longest, random_scale_prob=..., random_scale_range=..., random_aspect_prob=..., random_aspect_range=...) -> list[Any]:
        """Get parameters
        """
        ...
    
    def __call__(self, img) -> Tensor:
        """
        Args:
            img (PIL Image): Image to be cropped and resized.

        Returns:
            PIL Image: Resized, padded to at least target size, possibly cropped to exactly target size
        """
        ...
    
    def __repr__(self) -> str:
        ...
    


def center_crop_or_pad(img: torch.Tensor, output_size: List[int], fill=...) -> torch.Tensor:
    """Center crops and/or pads the given image.
    If the image is torch Tensor, it is expected
    to have [..., H, W] shape, where ... means an arbitrary number of leading dimensions.
    If image size is smaller than output size along any edge, image is padded with 0 and then center cropped.

    Args:
        img (PIL Image or Tensor): Image to be cropped.
        output_size (sequence or int): (height, width) of the crop box. If int or sequence with single int,
            it is used for both directions.
        fill (int, Tuple[int]): Padding color

    Returns:
        PIL Image or Tensor: Cropped image.
    """
    ...

class CenterCropOrPad(torch.nn.Module):
    """Crops the given image at the center.
    If the image is torch Tensor, it is expected
    to have [..., H, W] shape, where ... means an arbitrary number of leading dimensions.
    If image size is smaller than output size along any edge, image is padded with 0 and then center cropped.

    Args:
        size (sequence or int): Desired output size of the crop. If size is an
            int instead of sequence like (h, w), a square crop (size, size) is
            made. If provided a sequence of length 1, it will be interpreted as (size[0], size[0]).
    """
    def __init__(self, size, fill=...) -> None:
        ...
    
    def forward(self, img) -> Tensor:
        """
        Args:
            img (PIL Image or Tensor): Image to be cropped.

        Returns:
            PIL Image or Tensor: Cropped image.
        """
        ...
    
    def __repr__(self) -> str:
        ...
    


class MaybeConvertMode:
    """Perform PIL convert("RGB") iff PIL image.
    """
    def __init__(self, mode=...) -> None:
        ...
    
    def __call__(self, pic) -> ndarray[_Shape, dtype[Any]] | Tensor:
        """
        Args:
            pic (PIL Image or numpy.ndarray): Image to be converted to tensor.

        Returns:
            Tensor: Converted image.
        """
        ...
    
    def __repr__(self) -> str:
        ...
    


class MaybeToTensor(ToTensor):
    """Convert a PIL Image or ndarray to tensor if it's not already one.
    """
    def __init__(self) -> None:
        ...
    
    def __call__(self, pic) -> torch.Tensor:
        """
        Args:
            pic (PIL Image or numpy.ndarray): Image to be converted to tensor.

        Returns:
            Tensor: Converted image.
        """
        ...
    
    def __repr__(self) -> str:
        ...
    


class color_jitter:
    """
    Apply Color Jitter to the PIL image with a specified probability.
    """
    def __init__(self, brightness=..., contrast=..., saturation=..., hue=..., p=...) -> None:
        ...
    
    def __call__(self, img) -> Any:
        ...
    


class gray_scale:
    """
    Apply Gray Scale to the PIL image with a specified probability.
    """
    def __init__(self, p=...) -> None:
        ...
    
    def __call__(self, img) -> Any:
        ...
    


def image_transform(image_size: Union[int, Tuple[int, int]], is_train: bool, mean: Optional[Tuple[float, ...]] = ..., std: Optional[Tuple[float, ...]] = ..., resize_mode: Optional[str] = ..., interpolation: Optional[str] = ..., fill_color: int = ..., aug_cfg: Optional[Union[Dict[str, Any], AugmentationCfg]] = ...) -> TfPreprocessTransform | Compose | tuple[Compose, Compose, Compose]:
    ...

def image_transform_v2(cfg: PreprocessCfg, is_train: bool, aug_cfg: Optional[Union[Dict[str, Any], AugmentationCfg]] = ...) -> TfPreprocessTransform | Compose | tuple[Compose, Compose, Compose]:
    ...

