"""
This type stub file was generated by pyright.
"""

from typing import List, Optional, Tuple, Union

def freeze_batch_norm_2d(module, module_match=..., name=...) -> FrozenBatchNorm2d:
    """
    Converts all `BatchNorm2d` and `SyncBatchNorm` layers of provided module into `FrozenBatchNorm2d`. If `module` is
    itself an instance of either `BatchNorm2d` or `SyncBatchNorm`, it is converted into `FrozenBatchNorm2d` and
    returned. Otherwise, the module is walked recursively and submodules are converted in place.

    Args:
        module (torch.nn.Module): Any PyTorch module.
        module_match (dict): Dictionary of full module names to freeze (all if empty)
        name (str): Full module name (prefix)

    Returns:
        torch.nn.Module: Resulting module

    Inspired by https://github.com/pytorch/pytorch/blob/a5895f85be0f10212791145bfedc0261d364f103/torch/nn/modules/batchnorm.py#L762
    """
    ...

to_1tuple = ...
to_2tuple = ...
to_3tuple = ...
to_4tuple = ...
to_ntuple = ...
def replace_linear(model, linear_replacement, include_modules=..., copy_weights=...):
    ...

def convert_int8_model_to_inference_mode(model) -> None:
    ...

def feature_take_indices(num_features: int, indices: Optional[Union[int, List[int]]] = ..., as_set: bool = ...) -> Tuple[List[int], int]:
    """ Determine the absolute feature indices to 'take' from.

    Note: This function can be called in forward() so must be torchscript compatible,
    which requires some incomplete typing and workaround hacks.

    Args:
        num_features: total number of features to select from
        indices: indices to select,
          None -> select all
          int -> select last n
          list/tuple of int -> return specified (-ve indices specify from end)
        as_set: return as a set

    Returns:
        List (or set) of absolute (from beginning) indices, Maximum index
    """
    ...

