"""
This type stub file was generated by pyright.
"""

import torch
from typing import Callable, Optional, Sequence, Union

def batched(iterable, n) -> Generator[list[Any], Any, None]:
    """Batch data into lists of length *n*. The last batch may be shorter.
    NOTE based on more-itertools impl, to be replaced by python 3.12 itertools.batched impl
    """
    ...

def build_zero_shot_classifier(model, tokenizer, classnames: Sequence[str], templates: Sequence[Union[Callable, str]], num_classes_per_batch: Optional[int] = ..., device: Union[str, torch.device] = ..., use_tqdm: bool = ...) -> Tensor:
    """ Build zero-shot classifier weights by iterating over class names in batches
    Args:
        model: CLIP model instance
        tokenizer: CLIP tokenizer instance
        classnames: A sequence of class (label) names
        templates: A sequence of callables or format() friendly strings to produce templates per class name
        num_classes_per_batch: The number of classes to batch together in each forward, all if None
        device: Device to use.
        use_tqdm: Enable TQDM progress bar.
    """
    ...

def build_zero_shot_classifier_legacy(model, tokenizer, classnames: Sequence[str], templates: Sequence[Union[Callable, str]], device: Union[str, torch.device] = ..., use_tqdm: bool = ...) -> Tensor:
    """ Build zero-shot classifier weights by iterating over class names 1 by 1
    Args:
        model: CLIP model instance
        tokenizer: CLIP tokenizer instance
        classnames: A sequence of class (label) names
        templates: A sequence of callables or format() friendly strings to produce templates per class name
        device: Device to use.
        use_tqdm: Enable TQDM progress bar.
    """
    ...

