#!/usr/bin/env bash
set -euo pipefail

WATCH_PATH="/mnt/storage"
RULES_PATH="/etc/audit/rules.d/fanic-storage.rules"
RULE_KEY="fanic_storage"
DELETE_KEY="fanic_storage_delete"

usage() {
	cat <<'EOF'
Usage: scripts/setup-auditd-storage-watch.sh [options]

Options:
  --watch-path <path>   Directory to audit (default: /mnt/storage)
  --rules-path <path>   Destination audit rules file (default: /etc/audit/rules.d/fanic-storage.rules)
  --key <name>          Audit key for query filters (default: fanic_storage)
  --delete-key <name>   Audit key for deletion/rename events (default: fanic_storage_delete)
  -h, --help            Show this help

Example:
  sudo bash scripts/setup-auditd-storage-watch.sh --watch-path /mnt/storage --key fanic_storage --delete-key fanic_storage_delete
EOF
}

require_cmd() {
	local cmd="$1"
	if ! command -v "${cmd}" >/dev/null 2>&1; then
		echo "Required command not found: ${cmd}" >&2
		exit 1
	fi
}

while [[ $# -gt 0 ]]; do
	case "$1" in
	--watch-path)
		WATCH_PATH="$2"
		shift 2
		;;
	--rules-path)
		RULES_PATH="$2"
		shift 2
		;;
	--key)
		RULE_KEY="$2"
		shift 2
		;;
	--delete-key)
		DELETE_KEY="$2"
		shift 2
		;;
	-h | --help)
		usage
		exit 0
		;;
	*)
		echo "Unknown argument: $1" >&2
		usage
		exit 1
		;;
	esac
done

if [[ "${EUID}" -ne 0 ]]; then
	echo "This script must run as root (use sudo)." >&2
	exit 1
fi

if [[ ! -d "${WATCH_PATH}" ]]; then
	echo "Watch path does not exist: ${WATCH_PATH}" >&2
	exit 1
fi

require_cmd augenrules
require_cmd auditctl

if ! command -v ausearch >/dev/null 2>&1; then
	echo "warning: ausearch not found. Install auditd package for query tooling." >&2
fi

mkdir -p "$(dirname "${RULES_PATH}")"

cat >"${RULES_PATH}" <<EOF
## FANIC storage audit rules
## Generated by scripts/setup-auditd-storage-watch.sh
-a always,exit -F arch=b64 -S open -S openat -S openat2 -S creat -S truncate -S ftruncate -S unlink -S unlinkat -S rename -S renameat -S renameat2 -S mkdir -S mkdirat -S rmdir -F dir=${WATCH_PATH} -F perm=wa -k ${RULE_KEY}
-a always,exit -F arch=b64 -S unlink -S unlinkat -S rename -S renameat -S renameat2 -S rmdir -F dir=${WATCH_PATH} -F success=1 -k ${DELETE_KEY}
EOF

chmod 640 "${RULES_PATH}"

if command -v systemctl >/dev/null 2>&1; then
	if systemctl list-unit-files | grep -q '^auditd\.service'; then
		systemctl enable --now auditd >/dev/null 2>&1 || true
	fi
fi

augenrules --load

echo "Installed audit rules: ${RULES_PATH}"
echo "Watch path: ${WATCH_PATH}"
echo "Audit key: ${RULE_KEY}"
echo "Delete key: ${DELETE_KEY}"
echo "Active rules:"
auditctl -l | grep -E "${RULE_KEY}|${DELETE_KEY}" || true

echo ""
echo "Query recent events:"
echo "  sudo ausearch -k ${RULE_KEY} -i --start recent"
echo "  sudo ausearch -k ${DELETE_KEY} -i --start recent"
echo ""
echo "Query deletion-only events for a path:"
echo "  sudo ausearch -k ${RULE_KEY} -i --start recent -f ${WATCH_PATH}/fanart"
echo "  sudo bash scripts/query-auditd-deletions-summary.sh --since recent --path ${WATCH_PATH}/fanart"
echo ""
echo "Follow new audit events (journal):"
echo "  sudo journalctl -u auditd -f"
