"""
This type stub file was generated by pyright.
"""

from types import EllipsisType, ModuleType
from typing import Iterator
from pkgutil import ModuleInfo
from .base import *

"""Configuration module management... module.

- Add your own configurations by creating modules in the <root>.conf namespace package.
- Any value that is also defined in base.py will be overwritten by the value in the module.
- Configuration values will be accessible from the conf namespace package.
- The import order of the modules determines the resulting configuration.

Use like this (recommended for package mdules):

>>> from lazi.conf import conf
>>> conf.TRACE

Or like this (recommended for client modules):

>>> import lazi.conf.auto
>>> lazi.conf.TRACE
>>> from lazi.conf import auto
>>> auto.TRACE

But not like this:

>>> import lazi.conf        # This is not the same as the above.
>>> from lazi import conf   # Still no worky. Only imports the namespace module without loading.
"""
__all__ = ["base", "conf", "__root__", "__conf__", "__core__", "__auto__", "__keys__"]
if __name__ == "__main__":
    ...
base: ModuleType
__root__: ModuleType
__conf__: ModuleType
__core__: str
__auto__: str
__keys__: set
conf: dict
class Conf(ModuleType):
    __all__ = __all__
    __root__: ModuleType = ...
    __conf__: ModuleType = ...
    __core__: str = ...
    __auto__: str = ...
    __keys__: set = ...
    conf: dict[str, object | EllipsisType] = ...
    __mods: dict[str, ModuleType] = ...
    __CONF_NO_CACHING: bool = ...
    __CONF_NO_CACHING_DFL: bool = ...
    def __init__(self) -> None:
        ...

    def __iter__(self) -> Iterator[tuple[str, object]]:
        ...

    def get(self) -> dict:
        ...

    def clear(self) -> None:
        ...

    def __mods__(self) -> Iterator[ModuleInfo]:
        ...

    def __getattr__(self, attr: str) -> object:
        ...

    def __setattr__(self, attr: str, value: object) -> None:
        ...
