"""
This type stub file was generated by pyright.
"""

from pathlib import Path

"""
This type stub file was generated by pyright.
"""
SUPPORTED_IMAGE_EXTENSIONS: set[str]

def extract_comicinfo_metadata_from_cbz(cbz_path: Path) -> dict[str, object]: ...
def ingest_cbz(
    cbz_path: Path,
    metadata_override_path: Path | None = ...,
    uploader_username: str | None = ...,
) -> dict[str, object]: ...
def ingest_editor_page(
    image_path: Path,
    metadata: dict[str, object],
    uploader_username: str,
    work_id: str | None = ...,
) -> dict[str, object]: ...
