name: autopep695

on:
  push:
    paths:
      - "src/**/*.py"
      - "tests/**/*.py"
      - "pyproject.toml"
      - ".github/workflows/autopep695.yml"
  pull_request:
    paths:
      - "src/**/*.py"
      - "tests/**/*.py"
      - "pyproject.toml"
      - ".github/workflows/autopep695.yml"

jobs:
  autopep695:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Install uv
        uses: astral-sh/setup-uv@d31148d669074a8d0a63714ba94f3201e7020bc3

      - name: Run autopep695 check
        run: uvx autopep695 check src tests
